#!/usr/bin/env node
/**
 * seed-catalog.js
 * Extracts the MACHINES catalog from Sales-Portal.html and generates:
 *   - scripts/catalog-seed.sql  (Supabase INSERT statements)
 *   - scripts/catalog-data.json (clean JSON reference)
 */

const fs = require('fs');
const path = require('path');

// ── Paths ────────────────────────────────────────────────────────────────────
const ROOT = path.resolve(__dirname, '..');
const HTML_FILE   = path.join(ROOT, 'Sales-Portal.html');
const OUT_SQL     = path.join(__dirname, 'catalog-seed.sql');
const OUT_JSON    = path.join(__dirname, 'catalog-data.json');

// ── Helpers ──────────────────────────────────────────────────────────────────

/** Escape single quotes for SQL string literals */
function esc(str) {
  if (str == null) return '';
  return String(str).replace(/'/g, "''");
}

/** Truncate a string to maxLen chars */
function trunc(str, maxLen) {
  if (!str) return '';
  return str.length > maxLen ? str.slice(0, maxLen) : str;
}

/** Infer unit_condition from quoteTitle */
function inferCondition(title) {
  const upper = (title || '').toUpperCase();
  if (upper.includes('RE-CERTIFIED') || upper.includes('RECERTIFIED')) return 'Re-certified';
  if (upper.includes('DEMO UNIT') || upper.includes('DEMO'))           return 'Demo Unit';
  return 'Brand New';
}

/** Build INSERT lines for a child table (features, inclusions, exclusions, addons) */
function childInserts(tableName, midVar, items, limit = 50) {
  if (!items || items.length === 0) return '';
  const rows = items.slice(0, limit);
  const lines = rows.map((desc, i) =>
    `    INSERT INTO ${tableName} (machine_id, description, sort_order) VALUES (${midVar}, '${esc(trunc(desc, 500))}', ${i});`
  );
  return lines.join('\n');
}

/** Build INSERT lines for machine_consumables */
function consumableInserts(midVar, consumables, limit = 50) {
  if (!consumables || consumables.length === 0) return '';
  const rows = consumables.slice(0, limit);
  const lines = [];
  rows.forEach((c, i) => {
    const price = Number(c.price) || 0;
    if (price <= 0) return; // skip zero-price consumables
    const clampedPrice = Math.max(0.01, price);
    const itemName    = trunc(c.name || '', 150);
    const pkgDesc     = trunc(c.pkg  || '', 300);
    lines.push(
      `    INSERT INTO machine_consumables (machine_id, item_name, package_description, default_price, sort_order) VALUES (${midVar}, '${esc(itemName)}', '${esc(pkgDesc)}', ${clampedPrice}, ${i});`
    );
  });
  return lines.join('\n');
}

// ── Main ─────────────────────────────────────────────────────────────────────

console.log('Reading Sales-Portal.html …');
const html = fs.readFileSync(HTML_FILE, 'utf8');

// Extract the MACHINES JSON object.
// The variable assignment is on a single (very long) line: var MACHINES={...};
const match = html.match(/var MACHINES=(\{[\s\S]*?\});(?:var |<\/script>)/);
if (!match) {
  // Fallback: grab everything from 'var MACHINES=' up to the next 'var ' or </script>
  const startTag = 'var MACHINES=';
  const startIdx = html.indexOf(startTag);
  if (startIdx === -1) {
    console.error('ERROR: Could not find "var MACHINES=" in the HTML file.');
    process.exit(1);
  }

  // Walk forward to find the matching closing brace
  const jsonStart = startIdx + startTag.length;
  let depth = 0;
  let inStr = false;
  let escape = false;
  let end = -1;

  for (let i = jsonStart; i < html.length; i++) {
    const ch = html[i];
    if (escape) { escape = false; continue; }
    if (ch === '\\' && inStr) { escape = true; continue; }
    if (ch === '"' ) { inStr = !inStr; continue; }
    if (inStr) continue;
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) { end = i; break; }
    }
  }

  if (end === -1) {
    console.error('ERROR: Could not find the closing brace of MACHINES.');
    process.exit(1);
  }

  var machinesJson = html.slice(jsonStart, end + 1);
} else {
  var machinesJson = match[1];
}

console.log('Parsing MACHINES JSON …');
let MACHINES;
try {
  MACHINES = JSON.parse(machinesJson);
} catch (err) {
  console.error('ERROR: Failed to parse MACHINES JSON:', err.message);
  process.exit(1);
}

const keys = Object.keys(MACHINES);
console.log(`Found ${keys.length} machine entries.`);

// ── Process machines ─────────────────────────────────────────────────────────

const sqlBlocks   = [];
const jsonRecords = [];
let   processed   = 0;
let   skipped     = 0;

sqlBlocks.push('-- catalog-seed.sql');
sqlBlocks.push('-- Auto-generated by scripts/seed-catalog.js');
sqlBlocks.push('-- Run against your Supabase database to seed the machine catalog.');
sqlBlocks.push('');
sqlBlocks.push('BEGIN;');
sqlBlocks.push('');

for (const key of keys) {
  const m = MACHINES[key];

  // Skip placeholder/TBD entries
  const srp       = Number(m.srp)       || 0;
  const lbp       = Number(m.lbp)       || 0;
  const cashPrice = Number(m.cashPrice) || 0;
  if (srp === 0 && lbp === 0 && cashPrice === 0) {
    console.log(`  SKIP  ${key}  (all prices are 0)`);
    skipped++;
    continue;
  }

  const brand      = trunc(m.brand        || '', 100);
  const model      = trunc(m.quoteTitle   || key, 100);
  const condition  = inferCondition(m.quoteTitle);
  const letterhead = 'ES Print Media Inc.';

  const features   = Array.isArray(m.features)      ? m.features      : [];
  const inclusions = Array.isArray(m.stdPackages)    ? m.stdPackages   : [];
  const exclusions = Array.isArray(m.stdExclusives)  ? m.stdExclusives : [];
  const addons     = Array.isArray(m.optionals)
    ? m.optionals.map(o => (typeof o === 'object' ? (o.label || '') : String(o)))
    : [];
  const consumables = Array.isArray(m.consumables) ? m.consumables : [];

  // ── SQL block ──────────────────────────────────────────────────────────────
  const midVar = 'mid';
  const lines  = [];

  lines.push(`-- ${key}`);
  lines.push(`DO $$`);
  lines.push(`DECLARE`);
  lines.push(`  ${midVar} UUID;`);
  lines.push(`BEGIN`);
  lines.push(`  INSERT INTO machines (brand, model, sub_model, unit_condition, letterhead, is_active)`);
  lines.push(`  VALUES ('${esc(brand)}', '${esc(model)}', NULL, '${esc(condition)}', '${esc(letterhead)}', true)`);
  lines.push(`  ON CONFLICT DO NOTHING`);
  lines.push(`  RETURNING id INTO ${midVar};`);
  lines.push(``);
  lines.push(`  IF ${midVar} IS NOT NULL THEN`);

  const featSql = childInserts('machine_features',    midVar, features,   50);
  const inlSql  = childInserts('machine_inclusions',  midVar, inclusions, 50);
  const exlSql  = childInserts('machine_exclusions',  midVar, exclusions, 50);
  const addSql  = childInserts('machine_addons',      midVar, addons,     50);
  const conSql  = consumableInserts(midVar, consumables, 50);

  if (featSql) lines.push(featSql);
  if (conSql)  lines.push(conSql);
  if (inlSql)  lines.push(inlSql);
  if (exlSql)  lines.push(exlSql);
  if (addSql)  lines.push(addSql);

  lines.push(`  END IF;`);
  lines.push(`END $$;`);
  lines.push(``);

  sqlBlocks.push(lines.join('\n'));

  // ── JSON record ────────────────────────────────────────────────────────────
  const jsonConsumables = consumables
    .filter(c => Number(c.price) > 0)
    .slice(0, 50)
    .map(c => ({
      item_name:           trunc(c.name || '', 150),
      package_description: trunc(c.pkg  || '', 300),
      default_price:       Math.max(0.01, Number(c.price)),
    }));

  jsonRecords.push({
    brand,
    model,
    sub_model:    null,
    unit_condition: condition,
    letterhead,
    features:   features.slice(0, 50),
    consumables: jsonConsumables,
    inclusions: inclusions.slice(0, 50),
    exclusions: exclusions.slice(0, 50),
    addons:     addons.slice(0, 50),
  });

  processed++;
}

sqlBlocks.push('COMMIT;');
sqlBlocks.push('');

// ── Write outputs ─────────────────────────────────────────────────────────────

const sqlOutput = sqlBlocks.join('\n');
fs.writeFileSync(OUT_SQL, sqlOutput, 'utf8');
console.log(`\nWrote SQL  → ${OUT_SQL}  (${(sqlOutput.length / 1024).toFixed(1)} KB)`);

const jsonOutput = JSON.stringify(jsonRecords, null, 2);
fs.writeFileSync(OUT_JSON, jsonOutput, 'utf8');
console.log(`Wrote JSON → ${OUT_JSON}  (${(jsonOutput.length / 1024).toFixed(1)} KB)`);

console.log(`\nSummary:`);
console.log(`  Processed : ${processed}`);
console.log(`  Skipped   : ${skipped}`);
console.log(`  Total     : ${keys.length}`);
